## Preprocess

In [7]:
import pickle

dirname = "./data/classify/Classify_Example_0/preprocess_raw/"
filename = dirname + "event000001000.pickle"

[hits, truth] = pickle.load( open( filename, "rb" ) )

In [8]:
hits

hit_id            x           y            z  volume_id  layer_id  \
0       16878   -15.127200  -28.159300  -439.713989          8         2   
1       16896    -4.335470   32.314301  -439.015991          8         2   
2       16901   -31.529200    8.084200  -484.898010          8         2   
3       16919    31.209900   -4.953000  -355.386993          8         2   
4       16938   -31.227200   -7.444690  -282.063995          8         2   
...       ...          ...         ...          ...        ...       ...   
19451  117991  -937.254028  413.733002  1003.000000         17         4   
19452  117992  -939.736023  409.979004   981.400024         17         4   
19453  117993  -932.789978  409.071991  1003.000000         17         4   
19454  118002  -993.280029  235.123001  1035.400024         17         4   
19455  118007 -1022.280029   15.344300   981.400024         17         4   

       module_id  cell_count  cell_val      leta      lphi    lx        ly  \
0              3        39.0  2.065571  0.143280  1.498849  0.15   2.08125   
1             13        21.0  0.956484  0.299047  1.315082  0.25   0.95625   
2             16        52.0  2.791318  0.104322  1.535952  0.10   2.86875   
3             24        52.0  2.866749  0.102370  1.553704  0.05   2.92500   
4             33        48.0  2.602057  0.113152  1.532989  0.10   2.64375   
...          ...         ...       ...       ...       ...   ...       ...   
19451       3182         3.0  3.000000  0.064734  1.537475  0.36  10.80000   
19452       3182         2.0  2.000000  0.064754  1.548578  0.24  10.80000   
19453       3183         3.0  3.000000  0.064734  1.537475  0.36  10.80000   
19454       3187         1.0  1.000000  0.064766  1.559686  0.12  10.80000   
19455       3192         2.0  2.000000  0.064754  1.548578  0.24  10.80000   

        lz      geta      gphi  
0      0.3  2.524947 -1.556197  
1      0.3  1.628010  2.601884  
2      0.3  2.901340 -2.876192  
3      0.3  2.959407  0.108799  
4      0.3  2.820196 -2.483493  
...    ...       ...       ...  
19451  0.7  3.313360  3.032568  
19452  0.7  3.374970  2.887854  
19453  0.7  3.313359  3.073905  
19454  0.7  3.415965  2.934019  
19455  0.7  3.374971 -2.981964  

[19456 rows x 16 columns]

In [9]:
truth

hit_id         particle_id           tx          ty           tz  \
hit_id                                                                     
16877    16878  824170895156183040   -15.126400  -28.159700  -439.721985   
16895    16896  117109052193898496    -4.334720   32.314499  -439.022003   
16900    16901  171140359252869120   -31.529301    8.081720  -484.904999   
16918    16919  369301010599903232    31.210199   -4.947630  -355.397003   
16937    16938  860191583276892160   -31.227100   -7.444870  -282.071991   
...        ...                 ...          ...         ...          ...   
117990  117991  499899764796555264  -937.265991  413.716003  1007.950012   
117991  117992  684549548542001152  -939.710999  410.016998   979.002991   
117992  117993  499899764796555264  -932.760986  409.119995  1001.750000   
118001  118002  211676810348331008  -993.289978  235.097000  1036.989990   
118006  118007   27022422397943808 -1022.280029   15.346100   984.976990   

             tpx       tpy       tpz    weight        pt  
hit_id                                                    
16877  -0.149088 -0.154855 -1.379990  0.000012  1.396866  
16895   0.148277  0.980439 -2.633600  0.000033  2.814265  
16900  -0.247013 -0.047788 -2.269000  0.000011  2.283101  
16918   0.374076  0.026267 -3.552150  0.000014  3.571936  
16937  -0.232080 -0.064465 -2.105960  0.000008  2.120059  
...          ...       ...       ...       ...       ...  
117990 -0.544785  0.557897  0.752154  0.000010  1.095568  
117991 -0.995486  0.759998  1.182510  0.000017  1.820616  
117992 -0.547265  0.555872  0.751996  0.000009  1.095568  
118001 -1.779860  0.720691  1.933660  0.000027  2.734349  
118006 -0.977634  0.309131  0.974415  0.000015  1.441062  

[19456 rows x 10 columns]

## Doublet graphs

In [2]:
import numpy as np

In [3]:
dirname = "./data/classify/Classify_Example_0/doublet_graphs/"
filename = dirname + "event000001000_0.npz"

data = np.load( open( filename, "rb" ) )

In [14]:
for file in data.files:
    print(file)
    print(data[file])
    print(data[file].shape)

X
[[ 0.3618245   0.30053902  1.0378001 ]
 [ 0.3642835   0.3980689   1.0828    ]
 [ 0.3603519   0.79907227  0.99579996]
 ...
 [ 0.35913387 -0.9917474   0.97959995]
 [ 0.3638221   0.09568834  1.0225999 ]
 [ 0.36170083  0.29497004  1.0834    ]]
(2637, 3)
e
[[ 208  393   60 ... 1799 1702 1700]
 [1659 1659 1660 ... 1185 1186 1187]]
(2, 7043)
y
[1. 1. 0. ... 0. 1. 1.]
(7043,)


## Triplet graphs

In [15]:
dirname = "./data/classify/Classify_Example_0/triplet_graphs/"
filename = dirname + "event000001000_0.npz"

data = np.load( open( filename, "rb" ) )

In [16]:
for file in data.files:
    print(file)
    print(data[file])
    print(data[file].shape)

X
[[ 0.03372809 -0.9776921  -0.199096   ... -0.936007   -0.432018
   0.6144521 ]
 [ 0.03199971 -0.98081875 -0.188927   ... -0.936007   -0.432018
   0.8705214 ]
 [ 0.03171685 -0.4806075  -0.215317   ... -0.53553057 -0.484662
   0.3451962 ]
 ...
 [ 0.8233842  -0.49653816  0.8618     ... -0.6843071   1.0678
   0.98549265]
 [ 0.8196114   0.09232712  0.8402     ... -0.03326082  1.0461999
   0.9995653 ]
 [ 0.82381016 -0.8886714   0.7862     ... -1.0382195   0.9814
   0.99923635]]
(3311, 7)
e
[[ 446  238  237 ... 3214 3215 3213]
 [1301 1303 1303 ... 3308 3309 3310]]
(2, 3068)
y
[0. 1. 0. ... 1. 1. 1.]
(3068,)


## seed

In [20]:
dirname = "./data/classify/Classify_Example_0/seeds/"
filename = dirname + "event000001000.npy"

data = np.load( open( filename, "rb" ) )

In [26]:
print(data)
print(data.shape)

[[1.82170000e+04 2.62950000e+04 3.32520000e+04 8.46666813e-01]
 [1.75980000e+04 2.62950000e+04 3.32520000e+04 8.49061847e-01]
 [1.81890000e+04 2.63060000e+04 3.32540000e+04 7.80563772e-01]
 ...
 [9.63950000e+04 1.12358000e+05 1.17924000e+05 9.90751505e-01]
 [9.64120000e+04 1.12367000e+05 1.17933000e+05 9.66930568e-01]
 [9.61570000e+04 1.12367000e+05 1.17933000e+05 9.67156768e-01]]
(13097, 4)


## label

In [31]:
dirname = "./data/classify/Classify_Example_0/labels/"
filename = dirname + "event000001000.npy"

data = np.load( open( filename, "rb" ) )

In [32]:
print(data)
print(data.shape)

[[17598 17598]
 [18217 17598]
 [26295 26294]]
(3, 2)
